"""
Guards against the exact leakage-reporting regression found during review:
final_evaluation.py must report the leakage-safe retrieval similarity
(~0.52 avg / ~0.39 median), never the leaked raw similarity (~0.93/1.00)
that comes from evaluation_results.csv's retrieval_similarity column.

Requires outputs/leakage_safe_retrieval_results.csv to exist
(generated by `python -m src.evaluation`).
"""
import os
import unittest
import pandas as pd


class TestLeakageSafeRetrievalReporting(unittest.TestCase):

    def setUp(self):
        self.path = "outputs/leakage_safe_retrieval_results.csv"
        if not os.path.exists(self.path):
            self.skipTest("Run `python -m src.evaluation` first.")

    def test_similarity_is_not_leaked(self):
        df = pd.read_csv(self.path)
        avg_similarity = df["similarity"].mean()
        # The leaked (pre-exclusion) number is ~0.93. The leakage-safe
        # number should be meaningfully lower.
        self.assertLess(avg_similarity, 0.75)


if __name__ == "__main__":
    unittest.main()
